import operator 
from typing import Annotated,List,Dict,Optional,TypedDict,Any

class ComplianceIssue(TypedDict):
  category: str 
  description:str 
  severity:str 
  timestamp:Optional[str]

# This state will passed accross all node 
class VideoAuditState(TypedDict):

    '''
    Defines the data schema for langgraph execution content 
    '''
    # input to our project
    video_url:str 
    video_id:str 
    
    # analysis part , extraction and all 
    local_file_path: Optional[str]
    video_metadata : Dict[str,Any]
    transcript: Optional[str]
    ocr_text: List[str]
    
    # final deliverables 
    compliance_results: Annotated[List[ComplianceIssue],operator.add]  # store the  list of all compliance issues in video generated by ai
    
    # fianl one liner output -> PASS/FAIL
    final_status: str # PASS/FAIL
    final_report : str # markdown format 

    # system errors 
    errors : Annotated[List[str],operator.add]

    







